# Generated by Django 4.0.3 on 2022-03-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_addec_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='addec_on',
            new_name='added_on',
        ),
    ]
