# Generated by Django 4.0.3 on 2022-03-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item',
        ),
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.ManyToManyField(related_name='item', to='auctions.auction_listing'),
        ),
    ]
