# Generated by Django 4.0.3 on 2022-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_category_item_category_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
